site_name: K12 OCX Specification (Working Draft)
pages:
    - Home: index.md
    - Content Model: contentmodel.md
    - Manifest:
        - Aggregated content: manifest/index.md
        - Locating content: manifest/locate.md
        - Structuring aggregations: manifest/structure.md
    - In-page Markup:
        - In-page Markup: inpage/index.md
        - In-page structuring: inpage/structure.md
        - Course: inpage/course.md
        - Module: inpage/module.md
        - Unit: inpage/unit.md
        - Lesson: inpage/lesson.md
        - Activity: inpage/activity.md
        - Assessment: inpage/assessment.md
        - SupportingMaterial: inpage/supportingmaterial.md
        - Auxiliary Types: inpage/auxiliary-types.md
    - Packaging: packaging.md
    - Styling: styling.md
theme: readthedocs
extra_css:
    - css/custom.css
