site_name: K12 OCX Specification (Working Draft)
nav:
    - Home: index.md
    - Content Model: contentmodel.md
    - Manifest:
        - Aggregated content: manifest/index.md
        - Locating content: manifest/locate.md
        - Structuring aggregations: manifest/structure.md
    - In-page Markup:
        - In-page Markup: inpage/index.md
        - In-page structuring: inpage/structure.md
        - Properties of Course: inpage/course.md
        - Properties of Module: inpage/module.md
        - Properties of Unit: inpage/unit.md
        - Properties of Lesson: inpage/lesson.md
        - Properties of Activity: inpage/activity.md
        - Properties of Assessment: inpage/assessment.md
        - Properties of SupportingMaterial: inpage/supportingmaterial.md
        - Properties of SupplementalMaterial: inpage/supplementalmaterial.md
        - Properties of ReferencedMaterial: inpage/referencedmaterial.md
        - Properties of Auxiliary Types: inpage/auxiliary-types.md
    - Packaging: packaging.md
    - Styling: styling.md
theme: readthedocs
extra_css:
    - css/custom.css

markdown_extensions:
    - admonition
