site_name: K12 OCX Specification (Working Draft)
pages:
    - Home: index.md
    - Manifest:
        - About: manifest/about.md
        - Locating content: manifest/locate.md
        - Structuring content: manifest/structure.md
    - Metadata:
        - Semantic Markup: metadata/markup.md
        - Course: metadata/course.md
        - Module: metadata/module.md
        - Unit: metadata/unit.md
        - Lesson: metadata/lesson.md
        - Activity: metadata/activity.md
        - Assessment: metadata/assessment.md
        - SupportingMaterial: metadata/supportingmaterial.md
        - Auxiliary Types: metadata/auxiliary-types.md
    - Packaging: packaging.md
    - Styling: styling.md
theme: readthedocs
extra_css:
    - css/custom.css
